default: &default
  <<: *default
  database: postgres
  adapter: postgresql
  host: db
  encoding: unicode
  username: postgres
  password: senha

development:
  adapter: sqlite3
  database: db/db_dev_db.sqlite3
  pool: 5
  timeout: 5000 

test:
  <<: *default
  database: app_data
