default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development.sqlite3

test:
  <<: *default
  database: test.sqlite3

production:
  <<: *default
  database: production.sqlite3
